module.exports = {
  up: (queryInterface) => {
    return queryInterface.bulkInsert('Prices', [
      {
        productId: 1,
        supermarketId: 1,
        price: 11,
        active: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        productId: 2,
        supermarketId: 1,
        price: 21,
        active: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        productId: 3,
        supermarketId: 1,
        price: 31,
        active: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        productId: 4,
        supermarketId: 1,
        price: 41,
        active: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        productId: 5,
        supermarketId: 1,
        price: 51,
        active: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        productId: 6,
        supermarketId: 1,
        price: 61,
        active: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        productId: 7,
        supermarketId: 1,
        price: 31,
        active: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        productId: 8,
        supermarketId: 1,
        price: 81,
        active: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        productId: 9,
        supermarketId: 1,
        price: 91,
        active: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        productId: 10,
        supermarketId: 1,
        price: 101,
        active: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        productId: 11,
        supermarketId: 1,
        price: 111,
        active: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        productId: 12,
        supermarketId: 1,
        price: 121,
        active: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        productId: 13,
        supermarketId: 1,
        price: 251,
        active: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        productId: 14,
        supermarketId: 1,
        price: 61,
        active: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        productId: 15,
        supermarketId: 1,
        price: 271,
        active: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        productId: 16,
        supermarketId: 1,
        price: 281,
        active: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        productId: 17,
        supermarketId: 1,
        price: 261,
        active: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        productId: 18,
        supermarketId: 1,
        price: 41,
        active: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        productId: 19,
        supermarketId: 1,
        price: 41,
        active: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        productId: 20,
        supermarketId: 1,
        price: 41,
        active: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        productId: 21,
        supermarketId: 1,
        price: 41,
        active: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        productId: 22,
        supermarketId: 1,
        price: 71,
        active: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        productId: 23,
        supermarketId: 1,
        price: 71,
        active: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        productId: 24,
        supermarketId: 1,
        price: 311,
        active: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        productId: 1,
        supermarketId: 2,
        price: 10,
        active: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        productId: 2,
        supermarketId: 2,
        price: 20,
        active: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        productId: 3,
        supermarketId: 2,
        price: 30,
        active: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        productId: 4,
        supermarketId: 2,
        price: 40,
        active: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        productId: 5,
        supermarketId: 2,
        price: 50,
        active: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        productId: 6,
        supermarketId: 2,
        price: 60,
        active: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        productId: 7,
        supermarketId: 2,
        price: 30,
        active: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        productId: 8,
        supermarketId: 2,
        price: 80,
        active: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        productId: 9,
        supermarketId: 2,
        price: 90,
        active: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        productId: 10,
        supermarketId: 2,
        price: 100,
        active: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        productId: 11,
        supermarketId: 2,
        price: 110,
        active: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        productId: 12,
        supermarketId: 2,
        price: 120,
        active: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        productId: 13,
        supermarketId: 2,
        price: 250,
        active: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        productId: 14,
        supermarketId: 2,
        price: 60,
        active: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        productId: 15,
        supermarketId: 2,
        price: 270,
        active: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        productId: 16,
        supermarketId: 2,
        price: 280,
        active: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        productId: 17,
        supermarketId: 2,
        price: 260,
        active: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        productId: 18,
        supermarketId: 2,
        price: 40,
        active: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        productId: 19,
        supermarketId: 2,
        price: 40,
        active: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        productId: 20,
        supermarketId: 2,
        price: 40,
        active: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        productId: 21,
        supermarketId: 2,
        price: 40,
        active: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        productId: 22,
        supermarketId: 2,
        price: 70,
        active: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        productId: 23,
        supermarketId: 2,
        price: 70,
        active: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        productId: 24,
        supermarketId: 2,
        price: 310,
        active: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        productId:  1,
        supermarketId: 3,
        price: 10,
        active: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        productId:  2,
        supermarketId: 3,
        price: 20,
        active: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        productId:  3,
        supermarketId: 3,
        price: 30,
        active: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        productId:  4,
        supermarketId: 3,
        price: 9,
        active: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        productId:  5,
        supermarketId: 3,
        price: 9,
        active: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        productId:  6,
        supermarketId: 3,
        price: 9,
        active: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        productId:  7,
        supermarketId: 3,
        price: 9,
        active: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        productId:  8,
        supermarketId: 3,
        price: 9,
        active: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        productId:  9,
        supermarketId: 3,
        price: 9,
        active: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        productId:  10,
        supermarketId: 3,
        price: 19,
        active: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        productId:  11,
        supermarketId: 3,
        price: 19,
        active: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        productId:  12,
        supermarketId: 3,
        price: 19,
        active: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        productId:  13,
        supermarketId: 3,
        price: 29,
        active: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        productId:  14,
        supermarketId: 3,
        price: 9,
        active: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        productId:  15,
        supermarketId: 3,
        price: 29,
        active: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        productId:  16,
        supermarketId: 3,
        price: 29,
        active: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        productId:  17,
        supermarketId: 3,
        price: 29,
        active: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        productId:  18,
        supermarketId: 3,
        price: 9,
        active: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        productId:  19,
        supermarketId: 3,
        price: 9,
        active: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        productId:  20,
        supermarketId: 3,
        price: 9,
        active: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        productId:  21,
        supermarketId: 3,
        price: 9,
        active: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        productId:  22,
        supermarketId: 3,
        price: 9,
        active: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        productId:  23,
        supermarketId: 3,
        price: 9,
        active: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        productId: 24,
        supermarketId: 3,
        price: 39,
        active: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ]);
  },
  down: (queryInterface) => {
    return queryInterface.bulkDelete('Prices', null, {});
  },
};