module.exports = {
  up: (queryInterface) =>
    queryInterface.bulkInsert(
      'Products',
      [
        {
          categoryId:1,
          subcategoryId:1,
          measureId:5,
          quantity:80,
          title: 'Huggies· Toallas húmedas para bebé Cuidado Hidratante',
          description: 'Son las únicas con textura algodonosa y triple glicerina. Elaboradas con componentes naturales y 90% biodegradables, por lo que le brindan el máximo cuidado a la delicada piel del bebé, protegiéndola de manera eficiente mientras cuidan el medio ambiente. Hipoalergénicas. Sin Alcohol.',
          urlImage: 'https://s.cornershopapp.com/product-images/336131.jpg?versionId=QN1V2xUMayTeJ28TFaGyEjQmk7MVq_KP',
          active: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          categoryId:1,
          subcategoryId:1,
          measureId:5,
          quantity:36,
          title: 'Huggies · Pañales desechables etapa 6 para niño',
          description: 'Huggies Supreme Pure & Natural etapa 6 para niño. Los pañales Huggies son lo más avanzado en cuidado y protección gracias a su máxima suavidad y sus ingredientes naturales: Aloe, Manzanilla, Vitamina E y Avena Protec para consentir su delicada piel. Además con sus nuevas barreas SOft Care se ajustan delicadamente a la entrepierna evitando marcas rojas. Huggies Supreme Pure & Natural, dan protección, cuidado puro y natural. Recomendado para bebés de más de 13.5 kilogramos. Paquete con 36 pañales',
          urlImage: 'https://s.cornershopapp.com/product-images/221377.jpg',
          active: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          categoryId:1,
          subcategoryId:1,
          measureId:5,
          quantity:80,
          title: 'Bio Baby · Toallas húmedas',
          description: 'Sin perfume añadido, sin alcohol ni parabenos, suavidad premium. Piel sana: fórmula hipoalergénica con vitamina A y C. Eco-friendly, biodegradable. Paquete con 80 toallas húmedas.',
          urlImage: 'https://s.cornershopapp.com/product-images/313867.jpeg?versionId=nrjxx7ZtkMKHanwgchD2ZGPhdxqzHm6F',
          active: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          categoryId:1,
          subcategoryId:1,
          measureId:5,
          quantity:80,
          title: 'KleenBebé · Pañal Comodisec grande etapa 4',
          description: 'Pañales KleenBebé Comodisec unisex grande de 9 a 12 kg. Con aloe, manzanilla y vitamina E, más absorbente que nunca.',
          urlImage: 'https://s.cornershopapp.com/product-images/1129327.jpg?versionId=yf0k46PB8sRuyoiwHICEM7bUG.fqKkzK',
          active: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          categoryId:1,
          subcategoryId:1,
          measureId:5,
          quantity:38,
          title: 'Bio Baby · Pañales unisex talla 3 medianos',
          description: 'Pañales Bio Baby. Con suave cubierta externa y barreras antiescurrimientos que ofrecen el cuidado que la piel de tu bebé merece. Cuenta con un núcleo de celulosa y gel súper absorbente de rápida biodegradación. Y una fórmula que incluye aceites 100% naturales como el ylang-ylang, manzanilla, lavanda y geranio para un mayor cuidado y confort de la piel. Adicionalmente sus materiales biodegradables contribuyen a eliminar los desechos cuidando la ecología. Para niños y niñas de 7 a 10 kg.',
          urlImage: 'https://s.cornershopapp.com/product-images/341373.jpg?versionId=_GhqCO74B9g1hsjwELkJW9V8y_EDLXqu',
          active: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          categoryId:1,
          subcategoryId:2,
          measureId:1,
          quantity:113,
          title: 'Gerber · Papilla sabor ciruela pasa etapa 2',
          description: 'Papilla Gerber ciruela pasa ideal para los bebés, pues Gereber te ofrece papillas fortificadas con hierro para fomentar el desarrollo cognitivo de tu bebé, con la porción y textura adecuada para generar buenos hábitos alimenticios.',
          urlImage: 'https://s.cornershopapp.com/product-images/335360.jpg?versionId=.Yqo5dey1k6Snc20peXY14dBbGE0GPSN',
          active: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          categoryId:1,
          subcategoryId:2,
          measureId:1,
          quantity:100,
          title: 'Gerber · Papilla orgánica mango plátano',
          description: 'Alimento para lactantes, orgánico, a partir de los 6 meses.',
          urlImage: 'https://s.cornershopapp.com/product-images/1008230.jpg?versionId=IMc6GkhFzxvaHWnOJWCwHZM2mUEyhKJR',
          active: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          categoryId:1,
          subcategoryId:2,
          measureId:1,
          quantity:113,
          title: 'Gerber · Papilla sabor mango etapa 2',
          description: 'Las papillas 2DA. ETAPA® de GERBER® tiene nuevas variedades para tu bebé! Papillas fortificadas con hierro para fomentar el desarrollo mental de tu bebé y Vitamina C, con la porción y textura adecuada para generar buenos hábitos alimenticios. ¡Las papillas de 2DA. ETAPA® le aportarán la diversidad de nutrimentos que tu bebé necesita y están hechas con mango mexicano!^Recuerda que las papillas GERBER:^- Están hechas con ingredientes cosechados especialmente para tu bebé',
          urlImage: 'https://s.cornershopapp.com/product-images/335482.jpg?versionId=QJ02p7XKgMLSWxoU4Gr.yh9veR802.M1',
          active: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          categoryId:1,
          subcategoryId:2,
          measureId:1,
          quantity:115,
          title: 'Gerber · Papilla para Bebé Yogurt Etapa 2 sabor Durazno',
          description: 'Yogurt con papilla Gerber Yogolino 2da etapa durazno 115 g para lactantes, fortificado. Contiene calcio para huesos más fuertes.',
          urlImage: 'https://s.cornershopapp.com/product-images/206376.jpg',
          active: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          categoryId:1,
          subcategoryId:2,
          measureId:1,
          quantity:110,
          title: 'Gerber · Papilla sabor pera junior etapa 3',
          description: 'Pañales Bio Baby. Con suave cubierta externa y barreras antiescurrimientos que ofrecen el cuidado que la piel de tu bebé merece. Cuenta con un núcleo de celulosa y gel súper absorbente de rápida biodegradación. Y una fórmula que incluye aceites 100% naturales como el ylang-ylang, manzanilla, lavanda y geranio para un mayor cuidado y confort de la piel. Adicionalmente sus materiales biodegradables contribuyen a eliminar los desechos cuidando la ecología. Para niños y niñas de 7 a 10 kg.',
          urlImage: 'https://s.cornershopapp.com/product-images/277231.jpg?versionId=ftcNzyBc8P.eoLZncilRArGNelVJIOtD',
          active: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          categoryId:1,
          subcategoryId:3,
          measureId:7,
          quantity:200,
          title: 'Dove · Crema corporal baby humectación enriquecida',
          description: 'Crema corporal Baby Dove humectación enriquecida, con 24 horas de humectación profunda.',
          urlImage: 'https://s.cornershopapp.com/product-images/320857.jpg',
          active: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          categoryId:1,
          subcategoryId:3,
          measureId:7,
          quantity:250,
          title: 'Huggies · Jabón líquido 2 en 1 cuidado relajante',
          description: 'Huggies 2 en 1 shampoo + jabón líquido, con manzanilla y lavanda. Hipoalergénico, sin colorantes y libre de parabenos. Cuidado relajante.',
          urlImage: 'https://s.cornershopapp.com/product-images/1002182.jpg?versionId=NydrvL.yUI9CNKPyty0DhcAUob9QscxW',
          active: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          categoryId:1,
          subcategoryId:3,
          measureId:1,
          quantity:113,
          title: 'Bepanthen · Pomada protectora contra rozaduras dexpanthenol 5%',
          description: 'Bepanthen ayuda a la protección natural de la piel de tu bebé previniendo y aliviando las lesiones y rozaduras que provoca el uso del pañal.',
          urlImage: 'https://s.cornershopapp.com/product-images/338360.jpg?versionId=v8kOTVG2bbJDEmqGT0YHsS6KKiOrToNI',
          active: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          categoryId:1,
          subcategoryId:3,
          measureId:7,
          quantity:200,
          title: 'MENNEN · Shampoo clásico miel y extracto de manzanilla',
          description: 'Shampoo suave enriquecido con Miel y Extracto de Manzanilla que limpia, cuida y protege el cabello de toda la familia dejándolo con brillo y un agradable aroma.',
          urlImage: 'https://s.cornershopapp.com/product-images/332577.jpg?versionId=qMRrrweRSJpEOZAPw3vWrCMOwmPftMIx',
          active: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          categoryId:1,
          subcategoryId:3,
          measureId:1,
          quantity:150,
          title: 'Capent · Pomada para rozaduras de bebé hipoalergénica',
          description: 'Capent pomada para rozaduras, recomendada por pediatras. Alivia y previene las rozaduras formando una capa protectora.',
          urlImage: 'https://s.cornershopapp.com/product-images/374689.jpg?versionId=LDNrIjc3oizMlqbVi0FDEuvd1JvF7KvW',
          active: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          categoryId:1,
          subcategoryId:4,
          measureId:6,
          quantity:2,
          title: 'Zuum Baby · Set de cepillo y peine',
          description: 'Set de cepillo y peine para bebé Zuum Baby.',
          urlImage: 'https://s.cornershopapp.com/product-images/1046935.jpg?versionId=J8oNfE3WRbn15JvprgNGKB0lzC60r97L',
          active: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          categoryId:1,
          subcategoryId:4,
          measureId:7,
          quantity:60,
          title: 'Aggi · Desinfectante con plata coloidal',
          description: 'Desinfectante de juguetes y superficies para bebé.',
          urlImage: 'https://s.cornershopapp.com/product-images/1948038.jpg?versionId=c50zag25yd7c9brs6XS2.BklEQ4VMfvB',
          active: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          categoryId:1,
          subcategoryId:4,
          measureId:5,
          quantity:1,
          title: 'Zuum Baby · Tina para bebé',
          description: 'Color sujeto a disponibilidad en tienda.',
          urlImage: 'https://s.cornershopapp.com/product-images/1071040.jpg?versionId=nWi0dovuD02ikQsAIaedxjw3kUBImIXc',
          active: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          categoryId:1,
          subcategoryId:4,
          measureId:5,
          quantity:1,
          title: 'Nuby · Chupón Good Nite ortodóntico',
          description: 'Es perfecto para siestas y calmar al bebé por las noches. Su mango brilla en la oscuridad y tiene bordes en la tetina para brindar masaje.',
          urlImage: 'https://s.cornershopapp.com/product-images/89456.jpg',
          active: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          categoryId:1,
          subcategoryId:4,
          measureId:5,
          quantity:1,
          title: 'Evenflo · Biberón evenflo',
          description: '*Colores sujetos a disponibilidad* Biberón Evenflo 240 ml. Ayuda a reducir cólicos. Libre de BPA.',
          urlImage: 'https://s.cornershopapp.com/product-images/589671.jpg?versionId=O.3yGvz2i9d4MY0VAFKwrVhI2VVypadD',
          active: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          categoryId:2,
          subcategoryId:5,
          measureId:3,
          quantity:1,
          title: 'Alpura · Leche clásica entera',
          description: 'Leche Alpura 2000 Clásica. Leche parcialmente descremada, ultrapasteurizada. Adicionada con vitaminas A y D. Certificación Kosher.',
          urlImage: 'https://s.cornershopapp.com/product-images/335525.jpg?versionId=dk5qioCCEpI0Eb7Ra9ARSy04gB3Djl4h',
          active: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          categoryId:2,
          subcategoryId:5,
          measureId:3,
          quantity:1,
          title: 'Santa Clara · Leche light',
          description: 'Con sólo 5 grs. de grasa por litro, proporciona: Calcio, proteínas y vitaminas. Hecha con leche 100% de vaca.',
          urlImage: 'https://s.cornershopapp.com/product-images/306381.jpg?versionId=l6slpvmlOu9ixHX47GeMZyzLgmh_KO1c',
          active: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          categoryId:2,
          subcategoryId:5,
          measureId:3,
          quantity:1,
          title: 'Lala · Leche baja en grasa',
          description: 'Leche light ultrapasteurizada de Lala. Contiene nutrimentos esenciales para toda la familia como proteínas, vitaminas y minerales, entre ellos el calcio y son adicionadas con vitaminas A y D, indispensables en la alimentación diaria.',
          urlImage: 'https://s.cornershopapp.com/product-images/335735.jpg?versionId=y8oueJX0_D4_myQbzskIVJhOX6ynU1G.',
          active: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          categoryId:2,
          subcategoryId:5,
          measureId:7,
          quantity:200,
          title: 'Santa Clara · Leche sabor helado de chocolate',
          description: 'Esta leche está inspirada en el sabor de nuestro helado de chocolate. Hecho con leche 100% pura de vaca, sin colorantes ni saborizantes artificiales.',
          urlImage: 'https://s.cornershopapp.com/product-images/336102.jpg?versionId=RK2NgyecUYfmNli07eJS5QnnvjbYwH5E',
          active: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          categoryId:2,
          subcategoryId:5,
          measureId:7,
          quantity:200,
          title: 'Santa Clara · Leche sabor helado de fresa',
          description: 'Esta leche está inspirada en el sabor de nuestro helado de fresa. Hecho con leche 100% pura de vaca, sin colorantes ni saborizantes artificiales.',
          urlImage: 'https://s.cornershopapp.com/product-images/336160.jpg?versionId=1HyhpW8tS8Jf_0oaAHafCkZwSoXQGbzV',
          active: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          categoryId:2,
          subcategoryId:6,
          measureId:1,
          quantity:400,
          title: 'Lala · Queso manchego rebanado',
          description: 'Queso manchego rebanado de Lala, viene en empaque resellable que mantendrá tu queso fresco y en un estado perfecto.',
          urlImage: 'https://s.cornershopapp.com/product-images/335673.jpg?versionId=GpYPE574VWnbNFIWl8Xc7Ikenvk9XWZK',
          active: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          categoryId:2,
          subcategoryId:6,
          measureId:1,
          quantity:400,
          title: 'Nochebuena · Queso manchego rebanado',
          description: 'Queso manchego NocheBuena en rebanadas individuales 400 g.',
          urlImage: 'https://s.cornershopapp.com/product-images/335566.jpg?versionId=ioaYST9O6NIMZ_dGqGGGVzd3I.1PIBaa',
          active: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          categoryId:2,
          subcategoryId:6,
          measureId:1,
          quantity:400,
          title: 'Lala · Queso oaxaca',
          description: 'Esta leche está inspirada en el sabor de nuestro helado de fresa. Hecho con leche 100% pura de vaca, sin colorantes ni saborizantes artificiales.',
          urlImage: 'https://s.cornershopapp.com/product-images/334918.jpg?versionId=RuMI59SZLLnYMM9M1XKBZeRpDkmRebx3',
          active: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          categoryId:2,
          subcategoryId:6,
          measureId:1,
          quantity:250,
          title: 'Lala · Queso manchego rallado',
          description: 'Dale un toque delicioso a tus platillos con Lala y su queso tipo manchego. Su presentación rallada facilita su gratinado. Hecho con leche de vaca y con textura cremosa que se mezcla a la perfección con cualquier platillo. Su empaque resellable ayuda a que se mantenga fresco por más tiempo.',
          urlImage: 'https://s.cornershopapp.com/product-images/334929.jpg?versionId=JwD1OeYm1BV7pnzgbht1wgqkpS0AJ0QK',
          active: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          categoryId:2,
          subcategoryId:6,
          measureId:1,
          quantity:400,
          title: 'Los Volcanes · Queso panela',
          description: 'Los Volcanes · Queso panela 400g',
          urlImage: 'https://s.cornershopapp.com/product-images/335436.jpg?versionId=tIke.1.zFjLix2dudJsq5aTGNxge0jus',
          active: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          categoryId:2,
          subcategoryId:7,
          measureId:6,
          quantity:5,
          title: 'Yakult · Alimento lácteo fermentado',
          description: 'Yakult, alimento lácteo fermentado bebible natural. Contiene lactobacilus casei shirota.',
          urlImage: 'https://s.cornershopapp.com/product-images/137004.jpg',
          active: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          categoryId:2,
          subcategoryId:7,
          measureId:1,
          quantity:225,
          title: 'Activia · Yoghurt bebible fresa plátano y cereales',
          description: 'Yoghurt bebible Danone Activia fresa plátano y cereales 225 g, probiótico actirregularis, con fibra.',
          urlImage: 'https://s.cornershopapp.com/product-images/396129.jpg?versionId=Lm3f6xoTj_fCkAXaZLVOZqTCA55ua26R',
          active: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          categoryId:2,
          subcategoryId:7,
          measureId:1,
          quantity:120,
          title: 'Lala · Yoghurt griego zero sabor natural',
          description: 'Yoghurt natural batido tipo griego sin azúcar, que aporta 70 kcal de energía.',
          urlImage: 'https://s.cornershopapp.com/product-images/1902099.jpg?versionId=AjKNkTpa5Cl49DdBX2ak71ZLJjoC5mLE',
          active: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          categoryId:2,
          subcategoryId:7,
          measureId:1,
          quantity:900,
          title: 'Danone · Yoghurt natural sin azúcar',
          description: 'Yoghurt hecho con leche 100% mexicana, fermentos naturales y sin azucár. No contiene colorantes, saborizantes artificiales, edulcorantes ni conservadores. Opción ideal como ingrediente base para mezclar en recetas o ricas combinaciones.',
          urlImage: 'https://s.cornershopapp.com/product-images/368938.jpg?versionId=rOvbPLeY5zjqer0QeS_VGTcRj8GATsQV',
          active: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          categoryId:2,
          subcategoryId:7,
          measureId:6,
          quantity:6,
          title: 'Danone · Yoghurt con fresa',
          description: 'Hecho con frutas naturales con sabor a fresa. Su consumo regular te aporta una buena cantidad de calcio, además de que su presentación en botella es tan práctica que te permite llevarla a todas partes.',
          urlImage: 'https://s.cornershopapp.com/product-images/1150090.jpg?versionId=HkYbG6f_SnJZWrH0Fyz7L8nhS.eNHogT',
          active: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          categoryId:2,
          subcategoryId:8,
          measureId:6,
          quantity:30,
          title: 'Bachoco · Huevo blanco',
          description: 'Además de proteínas de alto valor biológico contienen vitaminas y minerales.',
          urlImage: 'https://s.cornershopapp.com/product-images/121885.jpg',
          active: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          categoryId:2,
          subcategoryId:8,
          measureId:6,
          quantity:30,
          title: 'El Calvario · Huevo blanco',
          description: 'Huevo blanco El Calvario con 30 piezas. Además de proteínas de alto valor biológico contienen vitaminas y minerales.',
          urlImage: 'https://s.cornershopapp.com/product-images/337465.jpg?versionId=HAkwLLMXJxLhHVfvwdt6o3ZXwrzZlTsi',
          active: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          categoryId:2,
          subcategoryId:8,
          measureId:6,
          quantity:30,
          title: 'Alvisa · Huevo blanco',
          description: 'Además de proteínas de alto valor biológico contienen vitaminas y minerales.',
          urlImage: 'https://s.cornershopapp.com/product-images/283723.jpg',
          active: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          categoryId:2,
          subcategoryId:8,
          measureId:6,
          quantity:12,
          title: 'El Calvario · Huevo blanco 12',
          description: 'Bandeja con 12 piezas. Además de proteínas de alto valor biológico contienen vitaminas y minerales.',
          urlImage: 'https://s.cornershopapp.com/product-images/121960.jpg',
          active: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          categoryId:3,
          subcategoryId:9,
          measureId:2,
          quantity:1,
          title: 'Selecta · Harina de trigo',
          description: 'Harina de trigo adicionada con ácido fólico, zinc y hierro. Restituida con vitamina B1, B2 y B3.',
          urlImage: 'https://s.cornershopapp.com/product-images/369712.jpg',
          active: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          categoryId:3,
          subcategoryId:9,
          measureId:1,
          quantity:110,
          title: 'Royal · Polvo para hornear',
          description: 'Royal · Polvo para hornear',
          urlImage: 'https://s.cornershopapp.com/product-images/1235073.png?versionId=bNYKsACg5AZ2xBUSCu8g02BYpY3rxrsF',
          active: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          categoryId:3,
          subcategoryId:9,
          measureId:6,
          quantity:12,
          title: 'Tres Estrellas · Harina de trigo integral con fibra natura',
          description: 'Harina de trigo Tres Estrellas Integral con fibra natural 1 kg. Especial para preparar galletas, pizzas, pasteles, tortillas, panadería, etcétera.',
          urlImage: 'https://s.cornershopapp.com/product-images/123452.jpg',
          active: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          categoryId:3,
          subcategoryId:9,
          measureId:1,
          quantity:500,
          title: 'Gamesa · Harina Hot Cake Tradicional',
          description: 'Gamesa · Harina Hot Cake Tradicional',
          urlImage: 'https://s.cornershopapp.com/product-images/274005.jpg',
          active: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          categoryId:3,
          subcategoryId:9,
          measureId:1,
          quantity:519,
          title: 'Betty Crocker · Harina preparada para brownies sabor chocolate',
          description: 'Harina para preparar brownie sabor a chocolate.',
          urlImage: 'https://s.cornershopapp.com/product-images/343120.jpg?versionId=7CaUbkT0a_jQQnGfmJ9LuNNMhHRQyJyU',
          active: true,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      {}
    ),

  down: (queryInterface) => queryInterface.bulkDelete('Products', null, {}),
};